#!/usr/bin/env bash

# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
# Custom HAProxy configuration
listen http-in
    bind :80
    balance roundrobin
    server web-01 34.239.250.75:80 check
    server web-02 100.25.17.31:80 check
EOL

# Enable HAProxy to be managed via init script
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy

# Restart HAProxy service
sudo service haproxy restart

