#!/usr/bin/env bash
# Display To infinity and beyond indefinitely receivingle  a SIGTERM signal

count=0

while ((count == 0));
do
	echo "To infinity and beyond"
	trap "echo I am invincible!!!" SIGTERM
	sleep 2
done
