#!/usr/bin/env bash
# This script displays "Best School" 10 times

counter=0

while ((counter < 10));
do
	if ((counter == 9));
    then
        echo "Hi"
    fi
    echo "Best School"
    ((counter++))
done
