#!/bin/bash

apt-get update
apt-get install -y nginx
service nginx stop
cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
sed -i 's/user www-data;/user www-data;/g' /etc/nginx/nginx.conf
service nginx start
ps aux | grep 'nginx: master process'
echo "Checking port 8080..."
nc -z 0 8080
echo $?

