#!/usr/bin/env bash
# SSH client configuration

# Apply the configuration globally
Host *
        PasswordAuthentication no
        IdentityFile ~/.ssh/school
        SendEnv LANG LC_*
        HashKnownHosts yes
        GSSAPIAuthentication yes
        GSSAPIDelegateCredentials no

